type QuoteType =
  | "citizen"
  | "fieldOfficerAccepted"
  | "fieldOfficerResolved";

const citizenQuotes: string[] = [
  "A cleaner Udupi begins with one caring citizen. Today, that citizen is you.",
  "You didn't look away. That matters more than you know.",
  "The Arabian Sea remembers every act of care.",
  "Small actions, taken together, are how cities change.",
  "You saw something, and you did something. That's civic courage.",
  "Udupi's coastline is protected by people like you.",
  "Every report is a vote for the city you deserve.",
  "You've just set something in motion. Watch what follows.",
  "The cleanup crew is on its way. You made that happen.",
  "Caring for a shared space is the most generous thing a person can do.",
  "One photo. One pin. One step toward a cleaner coast.",
  "This is what community looks like in action.",
  "The beach doesn't ask who will clean it. You answered anyway.",
  "Your report is already working — someone has been notified.",
  "It takes seconds to report, but the impact lasts far longer.",
  "Udupi's future is shaped by people who notice and act.",
  "You've done your part. The rest is in motion.",
  "Swachh Bharat isn't a slogan. It's what you just did.",
  "Civic responsibility isn't someone else's job. You just proved that.",
  "You turned concern into action. That's rare.",
  "Every kilometre of clean coastline has a story. You just added to it.",
  "Your neighbours will benefit from what you did today, even if they never know it.",
  "A healthy coast begins with someone willing to speak up.",
  "Thank you for making Udupi's beauty worth preserving.",
  "You gave the waste a record. Now it has nowhere to hide.",
  "The municipal team will take it from here. You started something good.",
  "This city cleans itself one act of kindness at a time.",
  "Pride in your place is the beginning of every improvement.",
  "Not everyone notices. Not everyone acts. You did both.",
  "Every cleaned beach in the world started with someone's report.",
  "You just made your ward a little more dignified.",
  "That pile of waste is now someone's priority because of you.",
  "The community grows stronger every time someone refuses to ignore the problem.",
  "Reporting waste isn't a complaint. It's an act of love for your city.",
  "Udupi has always been beautiful. You're helping keep it that way.",
  "Change doesn't wait for permission. It starts with a photo and a pin.",
  "You've shown that one person can make a ward better.",
  "There's no such thing as 'someone else's problem' when it comes to your city.",
  "The next child who plays on that beach won't know your name — but they'll benefit.",
  "A report submitted is a problem acknowledged. That's where all solutions begin.",
  "Civic pride isn't just a feeling. It's a practice. You just practiced it.",
  "Karnataka's coast is a treasure. You're one of its guardians today.",
  "Your action is on record. The cleanup will follow.",
  "What you did takes two minutes. The impact outlasts both of us.",
  "Responsibility is contagious. You just passed it on.",
  "The municipal team sees your report. Help is on its way.",
  "You believed the system could work, and so you used it. That belief matters.",
  "One waste pile reported is one less threat to the sea.",
  "This is your city. Today, you treated it like it.",
  "Kudos — you are helping the administration make Udupi a cleaner, prouder place.",
];

const fieldOfficerAcceptedQuotes: string[] = [
  "The community reported, you responded. That's the system working exactly as it should.",
  "Someone trusted that help would come. You're making that trust real.",
  "In progress means a promise kept.",
  "The report was a call. You picked up.",
  "Commitment starts the moment you accept the task.",
  "The citizen who reported this doesn't know your name — but they'll feel your work.",
  "Every ward you serve is a neighbourhood counting on you.",
  "The cleanup doesn't happen without someone deciding to start. You decided.",
  "Action taken is already half the battle won.",
  "Your uniform means something to this community. Today, you're proving it.",
  "Udupi's streets get cleaner because of people who show up.",
  "You accepted more than a task. You accepted responsibility.",
  "The coast has a champion today.",
  "Someone took the time to report. You took the time to act.",
  "Good officers don't wait. You're moving.",
  "This is service in its purest form — seen or unseen.",
  "The Arabian Sea doesn't clean itself. It depends on people like you.",
  "You've turned a report into a response. That's real progress.",
  "Every task you accept makes your ward a little more dignified.",
  "The citizen is watching. So is your ward. So is your character.",
  "Swachh Bharat is built one officer's commitment at a time.",
  "Hard work done quietly is still hard work. Thank you for showing up.",
  "Today's cleanup is tomorrow's pride.",
  "The moment you accepted this, someone's problem became your mission.",
  "Purpose looks like this — ordinary work done with genuine care.",
  "Not every hero is celebrated. Some just carry a mop and change the ward.",
  "The task is simple. The impact isn't. Go get it.",
  "Accepted means a community's hope is now in capable hands.",
  "Your district is cleaner because you exist. Don't forget that.",
  "This is what accountability looks like from the inside.",
  "Service before self. You're already living it.",
  "The waste won't clean itself. But with you on it, it will.",
  "Responsibility isn't given. It's taken. You just took it.",
  "Every officer who accepts a task adds to a district's dignity.",
  "The person who filed this report is somewhere hoping. You're their answer.",
  "Clean wards don't happen by accident. They happen because you said yes.",
  "You're the last line between that waste and the next high tide.",
  "It takes more than a system to clean a city. It takes a person who cares.",
  "The report is accepted. The work is real. So are you.",
  "What matters is that you showed up. Everything else follows.",
  "Karnataka's sanitation depends on the quiet commitment of officers like you.",
  "In this moment, you are Swachh Bharat.",
  "The hardest part is always starting. You've already done that.",
  "Every accepted task is a small act of leadership.",
  "You could have waited. You didn't. That's the difference.",
  "The waste doesn't care who cleans it. But the community cares that someone does.",
  "Your work today will outlast your memory of it.",
  "A ward is healthy when its officer is committed. Yours is.",
  "The task is small. The purpose behind it is enormous.",
  "You accepted a task. In doing so, you accepted your role in this city's story.",
];

const fieldOfficerResolvedQuotes: string[] = [
  "One less pile on Udupi's shore. That's not a small thing — it's everything.",
  "Done. The coast is a little cleaner. The community is a little better.",
  "You came, you cleaned, you moved on. That's what good service looks like.",
  "The waste is gone. Your work remains.",
  "This is what resolved looks like: a ward cleaner than you found it.",
  "You finished what someone else started by daring to report. Well done.",
  "The Arabian Sea just got a little more room to breathe.",
  "What you did today will matter to someone who will never know your name.",
  "Pride isn't always loud. Sometimes it's a clean street at the end of a shift.",
  "You turned a citizen's concern into a community's relief.",
  "Resolved isn't just a status. It's a promise kept.",
  "This is how Udupi gets better — one completed task at a time.",
  "The work is done. The impact lives on.",
  "You made someone's neighbourhood more dignified today.",
  "Every cleanup is a quiet act of service that speaks volumes.",
  "The beach remembers what you did. The sea is grateful.",
  "Your hands made a difference that data never fully captures.",
  "A task completed is a trust honoured.",
  "Not just clean — resolved. There's honour in that word.",
  "The citizen who reported this is sleeping a little better tonight.",
  "One more green pin on the map. One more reason to be proud.",
  "You didn't just clean up waste. You restored someone's faith in the system.",
  "Swachh Bharat is measured in moments like this one.",
  "The work is finished. The ward is better. That's all that needs to be said.",
  "A clean ward is a quiet triumph. Enjoy this one.",
  "You left a place better than you found it. That's the oldest form of service.",
  "Today's effort is tomorrow's standard. You've raised it.",
  "Udupi is a little more itself because of what you just did.",
  "Your name isn't on the wall, but your work is in the ward.",
  "The hardest part was showing up. The rest was you being you.",
  "Every resolved report is a brick in the foundation of a cleaner district.",
  "Done well, with purpose. That's what this was.",
  "You set out to solve a problem. You did. Go home proud.",
  "Karnataka needs officers who follow through. You are one of them.",
  "Impact doesn't always announce itself. Sometimes it's a cleaned alley and a closed report.",
  "The community sent a report. You sent a solution.",
  "Cleaned today means the waste won't reach the sea tomorrow.",
  "Your work is the reason people still trust this system.",
  "One task closed. One ward improved. One officer who made it count.",
  "The cleanup is done. The legacy, though small, is real.",
  "This is what it looks like when duty is taken seriously.",
  "You saw it through. Not everyone does. You did.",
  "Green is the best colour on a report card.",
  "A resolved report is a quiet victory for everyone who calls this place home.",
  "Every shift that ends this way makes the next one worth starting.",
  "Service with dignity means finishing what you start. You finished.",
  "The waste is gone. So is any doubt about whether good officers exist here.",
  "Well done isn't just an expression. In this case, it's literally true.",
  "Your contribution to Udupi is measured in clean wards and completed tasks. Today, both.",
  "The best thing about this job is moments like this one.",
];

const quotes: Record<QuoteType, string[]> = {
  citizen: citizenQuotes,
  fieldOfficerAccepted: fieldOfficerAcceptedQuotes,
  fieldOfficerResolved: fieldOfficerResolvedQuotes,
};

const lastIndexMap = new Map<QuoteType, number>();

export function getRandomMotivationalQuote(type: QuoteType): string {
  const pool = quotes[type];
  const lastIndex = lastIndexMap.get(type) ?? -1;

  let index: number;
  if (pool.length === 1) {
    index = 0;
  } else {
    do {
      index = Math.floor(Math.random() * pool.length);
    } while (index === lastIndex);
  }

  lastIndexMap.set(type, index);
  return pool[index];
}
